"""SQLAlchemy ORM models for KnowledgeBase, Document, and LifecycleTask."""

from __future__ import annotations

import enum
import uuid
from datetime import UTC, datetime

from sqlalchemy import (
    JSON,
    Boolean,
    DateTime,
    Enum,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


def _utcnow() -> datetime:
    return datetime.now(tz=UTC)


def _new_uuid() -> str:
    return uuid.uuid4().hex


# ---------------------------------------------------------------------------
# Base
# ---------------------------------------------------------------------------


class Base(DeclarativeBase):
    pass


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------


class KBStatus(enum.StrEnum):
    creating = "creating"
    ready = "ready"
    indexing = "indexing"
    rebuilding = "rebuilding"
    deleting = "deleting"
    deleted = "deleted"
    error = "error"


class DocumentStatus(enum.StrEnum):
    uploaded = "uploaded"
    parsing = "parsing"
    parsed = "parsed"
    indexing = "indexing"
    indexed = "indexed"
    rebuilding = "rebuilding"
    deleting = "deleting"
    deleted = "deleted"
    failed = "failed"


class TaskType(enum.StrEnum):
    parse = "parse"
    index = "index"
    reparse = "reparse"
    reindex = "reindex"
    rebuild = "rebuild"
    delete_document = "delete_document"
    delete_knowledge_base = "delete_knowledge_base"


class TaskStatus(enum.StrEnum):
    pending = "pending"
    running = "running"
    succeeded = "succeeded"
    failed = "failed"
    retrying = "retrying"
    cancelling = "cancelling"
    cancelled = "cancelled"


# ---------------------------------------------------------------------------
# Models
# ---------------------------------------------------------------------------


class KnowledgeBase(Base):
    __tablename__ = "knowledge_bases"

    id: Mapped[str] = mapped_column(
        String(32), primary_key=True, default=_new_uuid
    )
    name: Mapped[str] = mapped_column(String(200), nullable=False, default="")
    description: Mapped[str | None] = mapped_column(Text, nullable=True, default=None)

    status: Mapped[KBStatus] = mapped_column(
        Enum(KBStatus), nullable=False, default=KBStatus.creating
    )

    # Storage isolation — paths generated by StorageLayout, never from user input
    workspace_path: Mapped[str] = mapped_column(Text, nullable=False, default="")
    upload_path: Mapped[str] = mapped_column(Text, nullable=False, default="")
    parsed_path: Mapped[str] = mapped_column(Text, nullable=False, default="")

    # Parser / chunker snapshot
    parser_name: Mapped[str] = mapped_column(String(50), nullable=False, default="PyMuPDF")
    parser_version: Mapped[str | None] = mapped_column(String(30), nullable=True, default=None)
    chunking_strategy: Mapped[str] = mapped_column(String(50), nullable=False, default="fixed_character")
    chunking_version: Mapped[str] = mapped_column(String(20), nullable=False, default="1")
    chunking_config: Mapped[dict | None] = mapped_column(JSON, nullable=True, default=None)

    # Embedding snapshot
    embedding_model: Mapped[str] = mapped_column(String(50), nullable=False, default="text-embedding-v4")
    embedding_dimension: Mapped[int] = mapped_column(Integer, nullable=False, default=1024)

    # Counts (aggregated from documents / LightRAG)
    document_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    active_document_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    chunk_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    entity_count: Mapped[int | None] = mapped_column(Integer, nullable=True, default=None)
    relation_count: Mapped[int | None] = mapped_column(Integer, nullable=True, default=None)

    # Flags
    is_legacy_default: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    protect_from_delete: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow, onupdate=_utcnow
    )
    deleted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True, default=None
    )
    last_error: Mapped[str | None] = mapped_column(Text, nullable=True, default=None)

    # Relationships
    documents: Mapped[list[Document]] = relationship(
        "Document", back_populates="knowledge_base", lazy="selectin"
    )
    tasks: Mapped[list[LifecycleTask]] = relationship(
        "LifecycleTask", back_populates="knowledge_base", lazy="selectin"
    )

    def __repr__(self) -> str:
        return f"<KnowledgeBase id={self.id!r} name={self.name!r} status={self.status.value!r}>"


class Document(Base):
    __tablename__ = "documents"
    __table_args__ = (
        UniqueConstraint("knowledge_base_id", "file_hash", "is_active", name="uq_kb_active_hash"),
    )

    id: Mapped[str] = mapped_column(
        String(32), primary_key=True, default=_new_uuid
    )
    knowledge_base_id: Mapped[str] = mapped_column(
        String(32), ForeignKey("knowledge_bases.id"), nullable=False, index=True
    )

    # File info
    original_file_name: Mapped[str] = mapped_column(String(500), nullable=False)
    stored_file_name: Mapped[str] = mapped_column(String(200), nullable=False)
    file_path: Mapped[str] = mapped_column(Text, nullable=False, default="")
    file_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    file_size: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    mime_type: Mapped[str] = mapped_column(String(100), nullable=False, default="application/pdf")

    version: Mapped[int] = mapped_column(Integer, nullable=False, default=1)

    # Status
    status: Mapped[DocumentStatus] = mapped_column(
        Enum(DocumentStatus), nullable=False, default=DocumentStatus.uploaded
    )
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    parse_status: Mapped[str] = mapped_column(String(30), nullable=False, default="pending")
    index_status: Mapped[str] = mapped_column(String(30), nullable=False, default="pending")

    # Parser / chunker snapshot
    parser_name: Mapped[str] = mapped_column(String(50), nullable=False, default="PyMuPDF")
    parser_version: Mapped[str | None] = mapped_column(String(30), nullable=True, default=None)
    chunking_strategy: Mapped[str] = mapped_column(String(50), nullable=False, default="fixed_character")
    chunking_version: Mapped[str] = mapped_column(String(20), nullable=False, default="1")

    # Counts
    page_count: Mapped[int | None] = mapped_column(Integer, nullable=True, default=None)
    parent_chunk_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    child_chunk_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow, onupdate=_utcnow
    )
    indexed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True, default=None
    )
    deleted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True, default=None
    )
    last_error: Mapped[str | None] = mapped_column(Text, nullable=True, default=None)

    # Relationships
    knowledge_base: Mapped[KnowledgeBase] = relationship(
        "KnowledgeBase", back_populates="documents"
    )
    tasks: Mapped[list[LifecycleTask]] = relationship(
        "LifecycleTask", back_populates="document", lazy="selectin"
    )

    def __repr__(self) -> str:
        return (
            f"<Document id={self.id!r} kb={self.knowledge_base_id!r} "
            f"file={self.original_file_name!r} status={self.status.value!r}>"
        )


class LifecycleTask(Base):
    __tablename__ = "lifecycle_tasks"

    id: Mapped[str] = mapped_column(
        String(32), primary_key=True, default=_new_uuid
    )
    knowledge_base_id: Mapped[str] = mapped_column(
        String(32), ForeignKey("knowledge_bases.id"), nullable=False, index=True
    )
    document_id: Mapped[str | None] = mapped_column(
        String(32), ForeignKey("documents.id"), nullable=True, index=True
    )

    task_type: Mapped[TaskType] = mapped_column(Enum(TaskType), nullable=False)
    status: Mapped[TaskStatus] = mapped_column(
        Enum(TaskStatus), nullable=False, default=TaskStatus.pending
    )

    progress: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    current_stage: Mapped[str | None] = mapped_column(String(200), nullable=True, default=None)

    attempt: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    max_attempts: Mapped[int] = mapped_column(Integer, nullable=False, default=3)

    # Structured payload / result (JSON)
    payload: Mapped[dict | None] = mapped_column(JSON, nullable=True, default=None)
    result: Mapped[dict | None] = mapped_column(JSON, nullable=True, default=None)

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )
    started_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True, default=None
    )
    finished_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True, default=None
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow, onupdate=_utcnow
    )

    error_code: Mapped[str | None] = mapped_column(String(50), nullable=True, default=None)
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True, default=None)

    # Cleanup steps (JSON array of {step_name, status, attempt, error, completed_at})
    cleanup_steps: Mapped[list | None] = mapped_column(JSON, nullable=True, default=None)

    # Relationships
    knowledge_base: Mapped[KnowledgeBase] = relationship(
        "KnowledgeBase", back_populates="tasks"
    )
    document: Mapped[Document | None] = relationship(
        "Document", back_populates="tasks"
    )

    def __repr__(self) -> str:
        return (
            f"<LifecycleTask id={self.id!r} type={self.task_type.value!r} "
            f"status={self.status.value!r}>"
        )
